# Generated by Django 3.2.13 on 2022-04-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='habilidad',
            field=models.ManyToManyField(to='personas.Habilidades'),
        ),
    ]
