# Generated by Django 4.0.4 on 2022-05-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20220417_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fullname',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo'),
        ),
    ]
