# Generated by Django 4.0.4 on 2022-07-16 00:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto random'),
            preserve_default=False,
        ),
    ]
