# Generated by Django 4.0.4 on 2022-07-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_persona_hoja_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='puesto',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'OTRO')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
