# Generated by Django 4.0.4 on 2022-08-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_persona_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='persona'),
        ),
    ]
