# Generated by Django 4.0.4 on 2022-07-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_manufacturer_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
    ]
